// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/articles": {
    params: {};
  };
  "/articles/:id": {
    params: {
      "id": string;
    };
  };
  "/history": {
    params: {};
  };
  "/history/:id": {
    params: {
      "id": string;
    };
  };
  "/detection": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/articles/content": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/articles" | "/articles/:id" | "/history" | "/history/:id" | "/detection" | "/profile" | "/login" | "/register" | "/forgot-password" | "/reset-password" | "/auth/callback" | "/articles/content";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/articles.tsx": {
    id: "routes/articles";
    page: "/articles";
  };
  "routes/articles.$id.tsx": {
    id: "routes/articles.$id";
    page: "/articles/:id";
  };
  "routes/history.tsx": {
    id: "routes/history";
    page: "/history";
  };
  "routes/history.$id.tsx": {
    id: "routes/history.$id";
    page: "/history/:id";
  };
  "routes/detection.tsx": {
    id: "routes/detection";
    page: "/detection";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "routes/forgot-password.tsx": {
    id: "routes/forgot-password";
    page: "/forgot-password";
  };
  "routes/reset-password.tsx": {
    id: "routes/reset-password";
    page: "/reset-password";
  };
  "routes/auth.callback.tsx": {
    id: "routes/auth.callback";
    page: "/auth/callback";
  };
  "routes/articlecontent.tsx": {
    id: "routes/articlecontent";
    page: "/articles/content";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/articles": typeof import("./app/routes/articles.tsx");
  "routes/articles.$id": typeof import("./app/routes/articles.$id.tsx");
  "routes/history": typeof import("./app/routes/history.tsx");
  "routes/history.$id": typeof import("./app/routes/history.$id.tsx");
  "routes/detection": typeof import("./app/routes/detection.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "routes/forgot-password": typeof import("./app/routes/forgot-password.tsx");
  "routes/reset-password": typeof import("./app/routes/reset-password.tsx");
  "routes/auth.callback": typeof import("./app/routes/auth.callback.tsx");
  "routes/articlecontent": typeof import("./app/routes/articlecontent.tsx");
};